name: Build icons

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: "yarn"
            - run: yarn
            - run: make compile-from-figma
              env:
                  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
                  FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
            - run: yarn version --patch --no-commit-hooks --no-git-tag-version
            - run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
            - run: make publish-all
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  IGNORE_TOTP: 1
            - name: Upload changes...
              uses: EndBug/add-and-commit@v6
              with:
                  author_email: dothq-robot@users.noreply.github.com
                  author_name: dothq-robot
                  token: ${{ secrets.ROBOT_TOKEN }}
                  message: "🖼️ Update Foundation Icons from Figma"
